# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-04 12:01
from __future__ import unicode_literals

from django.db import migrations, models

def forwards_func(apps, schema_editor):
    Entry = apps.get_model('dictionary', 'Entry')
    db_alias = schema_editor.connection.alias
    for e in Entry.objects.using(db_alias).all():
        if e.questionable_headword or e.reconstructed_headword:
            orthvar = e.orthographic_variants.first()
            orthvar.reconstructed = e.reconstructed_headword
            orthvar.questionable = e.questionable_headword
            orthvar.save()

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0021_greq_aliud'),
    ]

    operations = [
        migrations.AddField(
            model_name='orthographicvariant',
            name='questionable',
            field=models.BooleanField(default=False, verbose_name='\u0420\u0435\u043a\u043e\u043d\u0441\u0442\u0440\u0443\u043a\u0446\u0438\u044f \u0432\u0430\u0440\u0438\u0430\u043d\u0442\u0430 \u0432\u044b\u0437\u044b\u0432\u0430\u0435\u0442 \u0441\u043e\u043c\u043d\u0435\u043d\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='orthographicvariant',
            name='reconstructed',
            field=models.BooleanField(default=False, verbose_name='\u0412\u0430\u0440\u0438\u0430\u043d\u0442 \u0440\u0435\u043a\u043e\u043d\u0441\u0442\u0440\u0443\u0438\u0440\u043e\u0432\u0430\u043d'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.RemoveField(
            model_name='entry',
            name='questionable_headword',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='reconstructed_headword',
        ),
        migrations.AlterField(
            model_name='entry',
            name='special_case',
            field=models.CharField(blank=True, choices=[(b'', b''), (b'a', '\u041d\u0435\u0441\u043a\u043e\u043b\u044c\u043a\u043e \u043b\u0435\u043a\u0441\u0435\u043c \u043e\u0434\u043d\u043e\u0433\u043e \u0440\u043e\u0434\u0430'), (b'b', '2 \u043b\u0435\u043a\u0441\u0435\u043c\u044b, \u043c\u0443\u0436. \u0438 \u0436\u0435\u043d. \u0440\u043e\u0434\u0430'), (b'c', '2 \u043b\u0435\u043a\u0441\u0435\u043c\u044b, \u0441\u0440. \u0438 \u0436\u0435\u043d. \u0440\u043e\u0434\u0430'), (b'g', '2 \u043b\u0435\u043a\u0441\u0435\u043c\u044b, \u0436\u0435\u043d. \u0438 \u0441\u0440. \u0440\u043e\u0434\u0430'), (b'd', '2 \u043b\u0435\u043a\u0441\u0435\u043c\u044b, \u0436\u0435\u043d. \u0438 \u0442\u043e\u043b\u044c\u043a\u043e \u043c\u043d.'), (b'e', '2 \u043b\u0435\u043a\u0441\u0435\u043c\u044b, \u0442\u043e\u043b\u044c\u043a\u043e \u043c\u043d. \u0438 \u0436\u0435\u043d.'), (b'f', '3 \u043b\u0435\u043a\u0441\u0435\u043c\u044b, 3 \u043c\u0443\u0436. \u0438 \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0438\u0439 \u043d\u0435\u0438\u0437\u043c.'), (b'h', '4 \u043b\u0435\u043a\u0441\u0435\u043c\u044b [\u0432\u0438\u0445\u0440\u044c]')], default='', max_length=1, verbose_name='\u0421\u0442\u0430\u0442\u044c\u044f \u043d\u0443\u0436\u0434\u0430\u0435\u0442\u0441\u044f \u0432 \u0441\u043f\u0435\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0439 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0435'),
        ),
        migrations.AlterField(
            model_name='meaning',
            name='special_case',
            field=models.CharField(blank=True, choices=[(b'', b''), ('\u0418\u043c\u0435\u043d\u0430', ((b'a', '\u043a\u0430\u043d\u043e\u043d\u0438\u0447.'), (b'h', '\u0438\u043c\u044f \u0441\u043e\u0431\u0441\u0442\u0432.'), (b'i', '\u0442\u043e\u043f\u043e\u043d\u0438\u043c'))), ('\u0427\u0430\u0441\u0442\u0438 \u0440\u0435\u0447\u0438', ((b'f', '\u043d\u0430\u0440\u0435\u0447.'), (b'm', '\u0441\u043e\u044e\u0437'), (b'b', '\u043f\u0440\u0435\u0434\u043b.'), (b'c', '\u0447\u0430\u0441\u0442.'), (b'g', '\u043c\u0435\u0436\u0434.'))), ('\u0424\u043e\u0440\u043c\u044b \u0441\u043b\u043e\u0432\u0430', ((b'd', '\u0434\u0430\u0442.'), (b'k', '\u043c\u043d.'), (b'e', '\u0442\u0432\u043e\u0440. \u0435\u0434. \u0432 \u0440\u043e\u043b\u0438 \u043d\u0430\u0440\u0435\u0447.'), (b'l', '\u0432 \u0440\u043e\u043b\u0438 \u043d\u0430\u0440\u0435\u0447.'))), ('\u0414\u0440\u0443\u0433\u043e\u0435', ((b'j', '\u043f\u0440\u0435\u0438\u043c\u0443\u0449.'),))], default=b'', max_length=1, verbose_name='\u043e\u0441\u043e\u0431\u044b\u0435 \u0441\u043b\u0443\u0447\u0430\u0438'),
        ),
    ]
