# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-18 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0022_auto_20180504_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='translation',
            field=models.TextField(blank=True, default='', verbose_name='\u041f\u0435\u0440\u0435\u0432\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='orthographicvariant',
            name='questionable',
            field=models.BooleanField(default=False, verbose_name='\u0440\u0435\u043a\u043e\u043d\u0441\u0442\u0440\u0443\u043a\u0446\u0438\u044f \u0432\u044b\u0437\u044b\u0432\u0430\u0435\u0442 \u0441\u043e\u043c\u043d\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='orthographicvariant',
            name='reconstructed',
            field=models.BooleanField(default=False, verbose_name='\u0440\u0435\u043a\u043e\u043d\u0441\u0442\u0440\u0443\u0438\u0440\u043e\u0432\u0430\u043d'),
        ),
    ]
