# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import slavdict.dictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0023_auto_20180518_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField(blank=True, default=1000, help_text='\u041d\u043e\u043c\u0435\u0440 \u0441\u043b\u043e\u0432\u0430, \u043f\u043e\u0441\u043b\u0435 \u043a\u043e\u0442\u043e\u0440\u043e\u0433\u043e \u0441\u043b\u0435\u0434\u0443\u0435\u0442 \u043f\u043e\u0441\u0442\u0430\u0432\u0438\u0442\u044c \u043f\u0435\u0440\u0435\u0432\u043e\u0434.', verbose_name='\u043f\u043e\u0437\u0438\u0446\u0438\u044f \u0432 \u043f\u0440\u0438\u043c\u0435\u0440\u0435')),
                ('order', models.SmallIntegerField(blank=True, default=345, verbose_name='\u043f\u043e\u0440\u044f\u0434\u043e\u043a \u0441\u043b\u0435\u0434\u043e\u0432\u0430\u043d\u0438\u044f')),
                ('hidden', models.BooleanField(default=True, help_text='\u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c \u043f\u0435\u0440\u0435\u0432\u043e\u0434 \u0442\u043e\u043b\u044c\u043a\u043e \u0432 \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u044f\u0445 \u0434\u043b\u044f \u0430\u0432\u0442\u043e\u0440\u043e\u0432', verbose_name='\u0441\u043a\u0440\u044b\u0432\u0430\u0442\u044c \u043f\u0435\u0440\u0435\u0432\u043e\u0434')),
                ('translation', models.TextField(verbose_name='\u043f\u0435\u0440\u0435\u0432\u043e\u0434')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': '\u043f\u0435\u0440\u0435\u0432\u043e\u0434',
                'verbose_name_plural': '\u041f\u0415\u0420\u0415\u0412\u041e\u0414\u042b',
            },
            bases=(models.Model, slavdict.dictionary.models.JSONSerializable),
        ),
        migrations.RemoveField(
            model_name='example',
            name='translation',
        ),
        migrations.AlterField(
            model_name='greekequivalentforexample',
            name='for_example',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greq_set', to='dictionary.Example'),
        ),
        migrations.AlterField(
            model_name='greekequivalentforexample',
            name='position',
            field=models.SmallIntegerField(blank=True, default=1000, help_text='\u041d\u043e\u043c\u0435\u0440 \u0441\u043b\u043e\u0432\u0430, \u043f\u043e\u0441\u043b\u0435 \u043a\u043e\u0442\u043e\u0440\u043e\u0433\u043e \u0441\u043b\u0435\u0434\u0443\u0435\u0442 \u043f\u043e\u0441\u0442\u0430\u0432\u0438\u0442\u044c \u043f\u0435\u0440\u0435\u0432\u043e\u0434.', verbose_name='\u043f\u043e\u0437\u0438\u0446\u0438\u044f \u0432 \u043f\u0440\u0438\u043c\u0435\u0440\u0435'),
        ),
        migrations.AddField(
            model_name='translation',
            name='for_example',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_set', to='dictionary.Example'),
        ),
    ]
