# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0024_auto_20180519_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='\u043f\u0440\u0438\u043c\u0435\u0447\u0430\u043d\u0438\u0435'),
        ),
    ]
