# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 19:00
from __future__ import unicode_literals

from django.db import migrations

def move_position_data(apps, schema_editor):
    Translation = apps.get_model('dictionary', 'Translation')
    for t in Translation.objects.all():
        t.fragment_end = t.position
        t.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0024_auto_20180523_1859'),
    ]

    operations = [
        migrations.RunPython(move_position_data),
    ]
