# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0025_auto_20180523_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='position',
        ),
    ]
