# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0030_auto_20180602_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='untitled_exists',
        ),
    ]
