# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0031_remove_entry_untitled_exists'),
    ]

    operations = [
        migrations.AddField(
            model_name='orthographicvariant',
            name='without_accent',
            field=models.BooleanField(default=False, verbose_name='\u0431\u0435\u0437 \u0443\u0434\u0430\u0440\u0435\u043d\u0438\u044f'),
        ),
    ]
