# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 18:12
from __future__ import unicode_literals

from django.db import migrations

def remove_singularia_tantum(apps, schema_editor):
    Entry = apps.get_model('dictionary', 'Entry')
    for e in Entry.objects.all():
        if e.tantum == 's':
            e.tantum = ''
            e.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0032_orthographicvariant_without_accent'),
    ]

    operations = [
        migrations.RunPython(remove_singularia_tantum),
    ]
