# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0034_tantum_rm_sg'),
    ]

    operations = [
        migrations.AddField(
            model_name='greekequivalentforexample',
            name='initial_form_phraseology',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u043d\u0430\u0447\u0430\u043b\u044c\u043d\u0430\u044f \u0444\u043e\u0440\u043c\u0430 \u0444\u0440\u0430\u0437\u0435\u043e\u043b\u043e\u0433\u0438\u0437\u043c\u0430'),
        ),
        migrations.AlterField(
            model_name='greekequivalentforexample',
            name='initial_form',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u043d\u0430\u0447\u0430\u043b\u044c\u043d\u0430\u044f \u0444\u043e\u0440\u043c\u0430 \u043b\u0435\u043a\u0441\u0435\u043c\u044b'),
        ),
    ]
