# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 11:26


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0035_auto_20180815_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='greek_eq_status',
            field=models.CharField(choices=[('L', '\u0441\u043b\u0435\u0434\u0443\u0435\u0442 \u043d\u0430\u0439\u0442\u0438'), ('S', '\u043d\u0435 \u043d\u0443\u0436\u043d\u044b'), ('C', '\u0443\u0442\u043e\u0447\u043d\u0438\u0442\u044c \u0430\u0434\u0440\u0435\u0441'), ('N', '\u043d\u0430\u0439\u0442\u0438 \u043d\u0435 \u0443\u0434\u0430\u043b\u043e\u0441\u044c'), ('P', '\u043a\u043e\u0433\u0434\u0430-\u043d\u0438\u0431\u0443\u0434\u044c \u043f\u043e\u0437\u0436\u0435, \u043e\u0442\u043b\u043e\u0436\u0435\u043d\u043d\u044b\u0435 \u043d\u0430 \u043f\u043e\u0442\u043e\u043c'), ('F', '\u043d\u0430\u0439\u0434\u0435\u043d\u044b'), ('M', '\u043d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u044b \u0434\u043b\u044f \u043e\u043f\u0440-\u044f \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f'), ('U', '\u0441\u0440\u043e\u0447\u043d\u043e\u0435')], default='L', max_length=1, verbose_name='\u043f\u0430\u0440\u0430\u043b\u043b\u0435\u043b\u0438'),
        ),
    ]
