# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-03 09:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0047_entry_comparative'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='is_synodal',
            field=models.BooleanField(default=False, verbose_name='\u0441\u0438\u043d\u043e\u0434\u0430\u043b\u044c\u043d\u044b\u0439 \u043f\u0435\u0440\u0435\u0432\u043e\u0434'),
        ),
    ]
