# Generated by Django 2.0.13 on 2019-12-12 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0050_auto_20191212_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='derivation_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_entry_set', to='dictionary.Entry', verbose_name='образовано от'),
        ),
        migrations.AlterField(
            model_name='example',
            name='collogroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.CollocationGroup'),
        ),
    ]
