# Generated by Django 2.2.12 on 2020-04-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0051_auto_20191212_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='source',
            field=models.CharField(choices=[('', ''), ('S', 'Синодальный перевод')], default='', max_length=1, verbose_name='Источник'),
        ),
    ]
