# Generated by Django 2.2.12 on 2020-04-23 10:08
'''
Миграция данных. Источник перевода в печатном словаре теперь может быть
указан не только для синодальной библии. Поэтому флаг "синодальности"
больше не нужен.
'''

from django.db import migrations

TRANSLATION_SOURCE_SYNODAL = 'S'


def forwards(apps, schema_editor):
    Translation = apps.get_model('dictionary', 'Translation')
    for t in Translation.objects.all():
        if t.is_synodal:
            t.source = TRANSLATION_SOURCE_SYNODAL
            t.save()


def backwards(apps, schema_editor):
    Translation = apps.get_model('dictionary', 'Translation')
    for t in Translation.objects.all():
        if t.source == TRANSLATION_SOURCE_SYNODAL:
            t.is_synodal = True
            t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0052_translation_source'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
