# Generated by Django 2.2.12 on 2020-04-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0053_data_synodal_to_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='is_synodal',
        ),
    ]
