# Generated by Django 2.2.12 on 2020-04-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0055_auto_20200424_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meaning',
            name='special_case',
            field=models.CharField(blank=True, choices=[('', ''), ('Имена', (('a', 'канонич.'), ('h', 'имя собств.'), ('i', 'топоним'))), ('Части речи', (('f', 'нареч.'), ('s', 'предик. нареч.'), ('m', 'союз'), ('b', 'предл.'), ('c', 'част.'), ('g', 'межд.'))), ('Формы слова', (('d', 'дат.'), ('k', 'мн.'), ('e', 'твор. ед. в роли нареч.'), ('l', 'в роли нареч.'), ('n', 'в роли прил.'), ('t', 'в роли союза'), ('o', 'в роли част.'))), ('Другое', (('q', 'безл.'), ('r', 'вводн.'), ('p', 'полувспом.'), ('j', 'преимущ.')))], default='', max_length=1, verbose_name='особые случаи'),
        ),
    ]
