# Generated by Django 2.2.17 on 2020-12-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_auto_20180307_1354'),
        ('dictionary', '0067_auto_20201217_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='temp_editors',
            field=models.ManyToManyField(blank=True, related_name='temp_editors_set', through='dictionary.TempEdit', to='custom_user.CustomUser', verbose_name='временные редакторы'),
        ),
    ]
