# Generated by Django 2.2.23 on 2021-06-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0073_auto_20210513_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meaning',
            name='special_case',
            field=models.CharField(blank=True, choices=[('', ''), ('Имена', (('a', 'канонич.'), ('h', 'имя собств.'), ('i', 'топоним'))), ('Части речи', (('v', 'мест.'), ('f', 'нареч.'), ('s', 'предик. нареч.'), ('m', 'союз'), ('b', 'предл.'), ('c', 'част.'), ('g', 'межд.'))), ('Формы слова', (('d', 'дат.'), ('k', 'мн.'), ('e', 'твор. ед. в роли нареч.'), ('l', 'в роли нареч.'), ('n', 'в роли прил.'), ('x', 'в роли действ. прич.'), ('w', 'в роли мест.'), ('t', 'в роли союза'), ('o', 'в роли част.'))), ('Другое', (('q', 'безл.'), ('r', 'вводн.'), ('u', 'плеоназм'), ('p', 'полувспом.'), ('j', 'преимущ.')))], default='', max_length=1, verbose_name='особые случаи'),
        ),
    ]
