# Generated by Django 2.2.23 on 2021-06-07 11:35

from django.db import migrations

BEYOND_DICT_STATUS = 'b'
CREATED_STATUS = 'c'

VOLUME_LETTERS = {
    1: ('а', 'б'),
    2: ('в',),
    3: ('г', 'д', 'е'),
    4: ('ж', 'з', 'и'),
    5: ('к', 'л', 'м'),
    6: ('н',),
    7: ('о',),
    8: ('п',),
    9: ('р', 'с'),
    10: ('т', 'у', 'ф', 'х', 'ц', 'ч', 'ш', 'щ', 'ю', 'я'),
}

def get_volume(entry):
    letter = entry.civil_equivalent.lstrip(' =*')[:1].lower()
    for volume, letters in VOLUME_LETTERS.items():
        if letter in letters:
            return volume
    return 0

def set_volume(apps, schema_editor):
    Entry = apps.get_model('dictionary', 'Entry')
    for e in Entry.objects.all():
        if e.status == BEYOND_DICT_STATUS:
            e.status = CREATED_STATUS
            e.volume = 0
        else:
            e.volume = get_volume(e)
        e.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0075_auto_20210607_1134'),
    ]

    operations = [
        migrations.RunPython(set_volume),
    ]
