# Generated by Django 2.2.23 on 2021-06-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0076_auto_20210607_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('c', 'создана'), ('w', 'в работе'), ('g', 'поиск греч.'), ('f', 'завершена'), ('e', 'редактируется'), ('a', 'утверждена')], default='c', max_length=1, verbose_name='статус статьи'),
        ),
    ]
