# Generated by Django 2.2.23 on 2021-06-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0077_auto_20210607_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='volume',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Вне томов'), (1, 'Том I (А, Б)'), (2, 'Том II (В)'), (3, 'Том III (Г, Д, Е)'), (4, 'Том IV (Ж, З, И)'), (5, 'Том V (К, Л, М)'), (6, 'Том VI (Н)'), (7, 'Том VII (О)'), (8, 'Том VIII (П)'), (9, 'Том IX (Р, С)'), (10, 'Том X (Т, У, Ф, Х, Ц, Ч, Ш, Щ, Ю, Я)')], default=0, verbose_name='том'),
        ),
    ]
