# Generated by Django 2.2.23 on 2021-10-02 15:49

from django.db import migrations

def migrate_template_version(apps, schema_editor):
    Entry = apps.get_model('dictionary', 'Entry')
    for entry in Entry.objects.filter(template_version=1):
        entry.template_version = 2
        entry.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0082_auto_20211002_1548'),
    ]

    operations = [
        migrations.RunPython(migrate_template_version),
    ]
