# Generated by Django 2.2.24 on 2022-01-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0083_auto_20211002_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='greek_eq_status',
            field=models.CharField(choices=[('L', 'следует найти'), ('S', 'не нужны'), ('C', 'уточнить адрес'), ('N', 'найти не удалось'), ('P', 'когда-нибудь позже, отложенные на потом'), ('F', 'найдены'), ('I', 'найдены (без указания начальных форм)'), ('M', 'необходимы для опр-я значения'), ('U', 'срочное')], default='L', max_length=1, verbose_name='параллели'),
        ),
    ]
