# Generated by Django 2.2.27 on 2022-02-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0084_auto_20220116_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='greek_eq_status',
            field=models.CharField(choices=[('L', 'следует найти'), ('S', 'не нужны'), ('C', 'уточнить адрес'), ('N', 'найти не удалось'), ('P', 'когда-нибудь позже, отложенные на потом'), ('F', 'найдены'), ('O', 'найдены (только для словосочетания)'), ('I', 'найдены (без указания начальных форм)'), ('M', 'необходимы для опр-я значения'), ('U', 'срочное')], default='L', max_length=1, verbose_name='параллели'),
        ),
    ]
