# Generated by Django 2.2.28 on 2023-10-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0088_auto_20230929_0016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('sort_key1', 'sort_key2', 'homonym_order'), 'verbose_name': 'словарная статья', 'verbose_name_plural': 'СЛОВАРНЫЕ СТАТЬИ'},
        ),
        migrations.AlterField(
            model_name='translation',
            name='source',
            field=models.CharField(blank=True, choices=[('', ''), ('S', 'Синодальный перевод'), ('R', 'Перевод РБО'), ('U', 'Перевод ПСТГУ'), ('M', 'Перевод братства преп. Иова Почаевского'), ('A', 'Адаменко В., свящ.'), ('Z', '(Безобразов) Кассиан, еп.'), ('B', 'Бируковы'), ('G', '(Говоров) Феофан, еп. — перевод Добротолюбия'), ('K', 'Кедров Н. — перевод великого канона'), ('V', 'Кулаков М.П. — перевод Нового Завета (Институт перевода Библии в Заокском)'), ('L', 'Ловягин Е.И. — перевод канонов'), ('2', 'Ловягин И.Ф. — перевод октоиха'), ('N', 'Нахимов Н. (Зайончковский Н.Ч.)'), ('E', 'Палехов Г. — перевод Известия учительного'), ('P', '(Полянский) Иустин, еп. — перевод Алфавита духовного'), ('3', 'Седакова О.А.'), ('T', '(Тимрот) Амвросий, иером.'), ('J', 'Юнгеров П.А.')], default='', max_length=1, verbose_name='Источник'),
        ),
    ]
