# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-19 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import slavdict.csl_annotations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', slavdict.csl_annotations.models.FixedWidthTextField(blank=True, help_text='\u041e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e \u0434\u043b\u044f \u0432\u0438\u0434\u0435\u043e, \u0444\u0430\u043a\u0443\u043b\u044c\u0442\u0430\u0442\u0438\u0432\u043d\u043e \u0434\u043b\u044f \u043a\u043d\u0438\u0433 \u0438 \u0441\u0442\u0430\u0442\u0435\u0439', max_length=200, null=True, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('bib', slavdict.csl_annotations.models.FixedWidthTextField(blank=True, help_text='\u0414\u043b\u044f \u043a\u043d\u0438\u0433 \u0438 \u0441\u0442\u0430\u0442\u0435\u0439', max_length=2000, null=True, verbose_name='\u0431\u0438\u0431\u043b\u0438\u043e\u0433\u0440\u0430\u0444\u0438\u0447\u0435\u0441\u043a\u0430\u044f \u0441\u0441\u044b\u043b\u043a\u0430')),
                ('annotation', models.TextField(blank=True, help_text='\u041e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e \u0434\u043b\u044f \u043a\u043d\u0438\u0433 \u0438 \u0441\u0442\u0430\u0442\u0435\u0439, \u0444\u0430\u043a\u0443\u043b\u044c\u0442\u0430\u0442\u0438\u0432\u043d\u043e \u0434\u043b\u044f \u0432\u0438\u0434\u0435\u043e', null=True, unique=True, verbose_name='\u0430\u043d\u043d\u043e\u0442\u0430\u0446\u0438\u044f')),
                ('teaser', models.TextField(blank=True, help_text='\u0414\u043b\u044f \u0432\u0438\u0434\u0435\u043e', null=True, unique=True, verbose_name='\u0442\u0438\u0437\u0435\u0440')),
                ('anchor', models.SlugField(blank=True, help_text='\n\n    \u042f\u043a\u043e\u0440\u044c, \u0447\u0442\u043e\u0431\u044b \u0441\u043e\u0441\u043b\u0430\u0442\u044c\u0441\u044f \u043d\u0430 \u0442\u0435\u043a\u0443\u0449\u0443\u044e \u0430\u043d\u043d\u043e\u0442\u0430\u0446\u0438\u044e \u0438\u0437 \u0434\u0440\u0443\u0433\u043e\u0439 \u0430\u043d\u043d\u043e\u0442\u0430\u0446\u0438\u0438.<br>\n    \u0415\u0441\u043b\u0438 \u0441\u0441\u044b\u043b\u043a\u0430\u0442\u044c\u0441\u044f \u043d\u0430 \u0434\u0430\u043d\u043d\u0443\u044e \u0430\u043d\u043d\u043e\u0442\u0430\u0446\u0438\u044e \u0438\u0437 \u0434\u0440\u0443\u0433\u043e\u0439 \u043d\u0435\u0442 \u043d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u0438,<br>\n    \u0442\u043e \u043f\u043e\u043b\u0435 \u043c\u043e\u0436\u043d\u043e \u043e\u0441\u0442\u0430\u0432\u043b\u044f\u0442\u044c \u043f\u0443\u0441\u0442\u044b\u043c.\n\n', max_length=30, null=True, unique=True, verbose_name='\u044f\u043a\u043e\u0440\u044c')),
                ('url', models.URLField(blank=True, help_text='\n\n    \u0423\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043b\u044e\u0431\u044b\u0435 \u0441\u0441\u044b\u043b\u043a\u0438 \u043a\u0440\u043e\u043c\u0435 \u044e\u0442\u044c\u044e\u0431\u043e\u0432\u0441\u043a\u0438\u0445.<br>\n    \u0421\u0441\u044b\u043b\u043a\u0438 \u043d\u0430 youtube \u0443\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u0432 \u043f\u043e\u043b\u0435 \xabID \u0432\u0438\u0434\u0435\u043e\xbb<br>\n    \u0432 \u0432\u0438\u0434\u0435 \u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440\u043e\u0432 \u0432\u0438\u0434\u0435\u043e.\n\n', max_length=1000, null=True, unique=True, verbose_name='\u0441\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0440\u0435\u0441\u0443\u0440\u0441')),
                ('youtube_id', models.CharField(blank=True, help_text='\n\n    \u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u0432\u0438\u0434\u0435\u043e \u043d\u0430 YouTube. \u041d\u0430\u043f\u0440\u0438\u043c\u0435\u0440, \u0435\u0441\u043b\u0438 \u0441\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0432\u0438\u0434\u0435\u043e \u0432\u044b\u0433\u043b\u044f\u0434\u0438\u0442<br>\n    \u0442\u0430\u043a <i>https://www.youtube.com/watch?v=zDRRSVplgXM&t=10s</i>,\n    \u0442\u043e \u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0442\u043e\u0440<br>\u0431\u0443\u0434\u0435\u0442 \u0432\u044b\u0433\u043b\u044f\u0434\u0435\u0442\u044c \u0432\u043e\u0442 \u0442\u0430\u043a <i>zDRRSVplgXM</i>.\n\n', max_length=20, null=True, unique=True, verbose_name='ID \u0432\u0438\u0434\u0435\u043e')),
            ],
            options={
                'verbose_name': '\u0430\u043d\u043d\u043e\u0442\u0430\u0446\u0438\u044f',
                'verbose_name_plural': '\u0430\u043d\u043d\u043e\u0442\u0430\u0446\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='\u0438\u043c\u044f')),
                ('second_name', models.CharField(blank=True, max_length=30, verbose_name='\u043e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('last_name', models.CharField(max_length=30, verbose_name='\u0444\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('title', slavdict.csl_annotations.models.FixedWidthTextField(blank=True, max_length=500, verbose_name='\u0442\u0438\u0442\u0443\u043b\u044b/\u0440\u0435\u0433\u0430\u043b\u0438\u0438')),
            ],
            options={
                'ordering': ('last_name', 'first_name', 'second_name'),
                'verbose_name': '\u0430\u0432\u0442\u043e\u0440',
                'verbose_name_plural': '\u0430\u0432\u0442\u043e\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u044f\u0440\u043b\u044b\u043a')),
                ('category', models.CharField(choices=[('a', '\u042d\u0442\u0430\u043f'), ('e', '\u0420\u0435\u0433\u0438\u043e\u043d'), ('i', '\u0422\u0435\u043a\u0441\u0442\u044b'), ('m', '\u041a\u043d\u0438\u0433\u0430'), ('q', '\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b'), ('u', '\u0418\u043d\u0441\u0442\u0440\u0443\u043c\u0435\u043d\u0442\u044b')], max_length=1, verbose_name='\u043a\u0430\u0442\u0435\u0433\u0440\u0438\u044f')),
                ('order', models.PositiveSmallIntegerField(default=10, help_text='\u041f\u043e\u0440\u044f\u0434\u043e\u043a \u0432 \u0440\u0430\u043c\u043a\u0430\u0445 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', verbose_name='\u043f\u043e\u0440\u044f\u0434\u043e\u043a')),
            ],
            options={
                'ordering': ('category', 'order', 'id'),
                'verbose_name': '\u0431\u0438\u0440\u043a\u0430',
                'verbose_name_plural': '\u0431\u0438\u0440\u043a\u0438',
            },
        ),
        migrations.AddField(
            model_name='annotation',
            name='authors',
            field=models.ManyToManyField(blank=True, to='csl_annotations.Author', verbose_name='\u0430\u0432\u0442\u043e\u0440\u044b'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='tags',
            field=models.ManyToManyField(to='csl_annotations.Tag', verbose_name='\u0442\u044d\u0433\u0438'),
        ),
    ]
