# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-20 23:13


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csl_annotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='url',
            field=models.CharField(blank=True, help_text='\n\n    \u0423\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043b\u044e\u0431\u044b\u0435 \u0441\u0441\u044b\u043b\u043a\u0438 \u043a\u0440\u043e\u043c\u0435 \u044e\u0442\u044c\u044e\u0431\u043e\u0432\u0441\u043a\u0438\u0445.<br>\n    \u0421\u0441\u044b\u043b\u043a\u0438 \u043d\u0430 youtube \u0443\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u0432 \u043f\u043e\u043b\u0435 \xabID \u0432\u0438\u0434\u0435\u043e\xbb<br>\n    \u0432 \u0432\u0438\u0434\u0435 \u0438\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440\u043e\u0432 \u0432\u0438\u0434\u0435\u043e.\n\n', max_length=1000, null=True, unique=True, verbose_name='\u0441\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0440\u0435\u0441\u0443\u0440\u0441'),
        ),
        migrations.AlterField(
            model_name='taggroup',
            name='parent_tag',
            field=models.ForeignKey(help_text='\u0411\u0438\u0440\u043a\u0430, \u043a \u043a\u043e\u0442\u043e\u0440\u043e\u0439 \u043e\u0442\u043d\u043e\u0441\u0438\u0442\u0441\u044f \u0433\u0440\u0443\u043f\u043f\u0430.', on_delete=django.db.models.deletion.CASCADE, to='csl_annotations.Tag', verbose_name='\u0440\u043e\u0434\u0438\u0442\u0435\u043b\u044c\u0441\u043a\u0430\u044f \u0431\u0438\u0440\u043a\u0430'),
        ),
    ]
