# Generated by Django 2.0.13 on 2019-12-12 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csl_annotations', '0006_auto_20191104_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='csl_annotations.Tag', verbose_name='бирка-родитель'),
        ),
    ]
